name: Build container image
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
      - ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build
        run: ./gradlew bootBuildImage
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Tag image
        run: docker tag ${{ github.repository }} ghcr.io/${{ github.repository }}:latest
      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}:latest